version: '3.3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./database.sqlite:/app/database.sqlite
      - ./estimates.db:/app/estimates.db
    environment:
      - NODE_ENV=production
    restart: unless-stopped
