version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://unifi.kc2vrj.com:3000
      - NEXTAUTH_SECRET=estimatepro_secret_key_123
      - DATABASE_PATH=/app/data/estimates.db
      # Optional SSL configuration
      - #SSL_DOMAIN=${SSL_DOMAIN:-}
      - SSL_DOMAIN=unifi.kc2vrj.com
      - SSL_EMAIL=pnannery@gmail.com
      #- SSL_EMAIL=${SSL_EMAIL:-}
      
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
